name: Release

on:
  push:
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: recursive

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
            node-version: ${{ matrix.node-version }}

      - name: Get the version
        id: get-version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          npm install
          sudo apt-get -y install llvm

      - name: Build CLI karel
        run: |
          npm run build:bundle
          tar cJf dist/karel.js.tar.xz '--transform=s/dist\///' dist/*.js dist/*.node

      - name: Build distributable .zip
        run: |
          zip --recurse-paths dist/karel.zip \
            cmd/ css/ gramaticas/ img/ js/ lib/ manual/ LICENSE ayuda.html \
            sandbox.html README.md index.html

      - name: Build C++ karel
        run: |
          (cd cpp && make karel)

      - name: Create Release
        id: create-release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload karel.zip Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist/karel.zip
          asset_name: karel.zip
          asset_content_type: application/octet-stream

      - name: Upload karel.js.tar.xz Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist/karel.js.tar.xz
          asset_name: karel.js.tar.xz
          asset_content_type: application/octet-stream

      - name: Upload karel Release Asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./cpp/karel
          asset_name: karel
          asset_content_type: application/octet-stream
